<?php

declare(strict_types=1);

namespace Library;

use WoLfulus\Extras\Package;

/**
 * Library
 */
class Library {
    /**
     * Plugins
     */
    protected $plugins = [];

    /**
     * Initialize
     */
    public function __construct()
    {
        $this->plugins = Plugins::get(); // This class will be generated by extras
    }

    /**
     * Gets all plugin messages.
     */
    public function messages(): array {

        $messages = [];
        foreach ($this->plugins as $plugin) {
            $data = $plugin->data();
            if (!isset($data['plugins'])) {
                continue;
            }

            $classes = $data['plugins'];
            foreach ($classes as $class) {
                /** @var Plugin $instance */
                $instance = new $class();
                $messages[] = $instance->message();
            }
        }

        return $messages;
    }
}
